version: "3.1"

services:
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "3300:80"
    links:
      - first-server
      - second-server
  database:
    image: mongo # imaj adı
    ports:
      - "9000:27017"
  rabbitmq: # Rabbit Mq server için tanımlama
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    ports:
      - "9003:15672"
  queue:
    build:
      context: ./queue
      dockerfile: queue.Dockerfile
    ports:
      - "5000:3000"
    links:
      - rabbitmq
  first-server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    ports:
      - "3500:3000"
    links:
      - database
      - queue
  second-server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    ports:
      - "3400:3000"
  client:
    build:
      context: ./client
      dockerfile: client.Dockerfile
    ports:
      - "3600:3000"
    links:
      - proxy
      - queue
