version: "3.1"

services: # Tüm Docker container'larımız 'services' altında olacak
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3300:80"
    links:
      - first-server
      - second-server
    restart: always
  database: # Mongo server için tanımlama
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports: # port yönlendirmeleri
      - "9000:27017"
    restart: always
  database-seed:
    build:
      context: ./database-seed
      dockerfile: Dockerfile
    links:
      - database
  rabbitmq: # Rabbit Mq server için tanımlama
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports: # port yönlendirmeleri
      - "9003:15672"
    restart: always
  queue: # Queue server için tanımlama
    build:
      context: ./queue
      dockerfile: Dockerfile
    ports: # port yönlendirmeleri
      - "5000:3000"
    links:
      - rabbitmq
    restart: always
  first-server: # İlk Express server için tanımlama
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: # port yönlendirmeleri
      - "3500:3000"
    links:
      - database
      - queue
    restart: always
  second-server: # İkinci Express server için tanımlama
    build:
      context: ./server
      dockerfile: Dockerfile
    ports: # port yönlendirmeleri
      - "3400:3000"
    restart: always
  client: # react client için tanımlama
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: # port yönlendirmeleri
      - "3600:3000"
    links:
      - proxy
      - queue
    restart: always